Repository redBorder/rb-aioutliers, pull requests merged in 2023-09, with the labels that each got.

#1 GitHub Actions Test
  .github/workflows/tests.yml
Labels: enhancement

#2 actions on push and pr
  .github/workflows/tests.yml
Labels: enhancement

#3 Safety Checks and some tests
  .github/workflows/tests.yml
  README.md
  resources/src/Logger/logger.py
  resources/src/requirements.txt
  resources/tests/test_configmanager.py
  resources/tests/test_druid.py
  resources/tests/test_logger.py
Labels: enhancement

#4 Update README.md
  README.md
Labels: documentation

#5 Run outliers job
  .github/workflows/tests.yml
  resources/src/__main__.py
  resources/src/config.ini
  resources/src/server/rest.py
Labels: enhancement

#6 Ng integration
  resources/src/IA/outliers.py
  resources/src/IA/traffic.ini
  resources/src/IA/traffic.keras
  resources/src/server/rest.py
Labels: enhancement

#7 Add tests to autoencoder execution
  resources/src/Druid/aggregations.json
  resources/src/Druid/postAggregations.json
  resources/src/__main__.py
  resources/src/server/rest.py
  resources/tests/outliers_test_data.json
  resources/tests/test_outliers.py
Labels: enhancement

#8 Update Makefile and spec file
  .gitignore
  Makefile
  packaging/rpm/Makefile
  packaging/rpm/rb-aioutliers.spec
Labels: enhancement

#9 Linter action
  .github/workflows/lint.yml
  resources/src/IA/outliers.py
  resources/src/Logger/logger.py
  resources/src/server/rest.py
Labels: enhancement

#10 Security workflow
  .github/workflows/security.yml
  .github/workflows/tests.yml
Labels: enhancement

#11 Ai model development
  resources/src/Druid/aggregations.json
  resources/src/Druid/postAggregations.json
  resources/src/Druid/query_builder.py
  resources/src/IA/autoencoder.keras
  resources/src/IA/outliers.py
  resources/src/server/rest.py
  resources/tests/test_druid.py
  resources/tests/test_query_builder.py
Labels: enhancement

#12 Update spec file
  packaging/rpm/rb-aioutliers.spec
Labels: documentation

#13 Fix spec file changelog
  packaging/rpm/rb-aioutliers.spec
Labels: bug

#15 Prepare service for production environments
  .github/workflows/tests.yml
  resources/src/__main__.py
  resources/src/ai/outliers.py
  resources/src/ai/traffic.ini
  resources/src/ai/traffic.keras
  resources/src/config.ini
  resources/src/config/configmanager.py
  resources/src/druid/aggregations.json
  resources/src/druid/client.py
  resources/src/druid/postAggregations.json
  resources/src/druid/query_builder.py
  resources/src/logger/logger.py
  resources/src/redborder/client.py
  resources/src/requirements.txt
  resources/src/server/production.py
  resources/src/server/rest.py
  resources/systemd/rb-aioutliers.service
  resources/tests/test_configmanager.py
  resources/tests/test_druid.py
  resources/tests/test_logger.py
  resources/tests/test_outliers.py
  resources/tests/test_query_builder.py
  resources/tests/test_redborder_api.py
Labels: feature
