Repository redBorder/rb-aioutliers, pull requests merged in 2023-10, with the labels that each got.

#16 Add training
  resources/src/ai/trainer.py
  resources/src/logger/logger.py
  resources/tests/model_test.keras
  resources/tests/model_test_config.ini
  resources/tests/test_outliers.py
  resources/tests/test_trainer.py
Labels: enhancement

#17 Update outliers documentation after training merged
  README.md
Labels: kind/documentation, size/XS

#20 PR-20: Update CI workflow
  .github/workflows/lint.yml
  .github/workflows/pr.yml
  .github/workflows/security.yml
  .github/workflows/tests.yml
Labels: size/M, kind/feature

#21 PR-21: Update CI to skip validation of PR for dependabot
  .github/workflows/pr.yml
Labels: enhancement, size/XS

#25 PR-25: Update documentation for add info about deleting the model design
  README.md
Labels: kind/documentation, size/XS

#26 PR-26: Add docker support
  README.md
  resources/src/Dockerfile
  resources/src/docker-compose.yml
Labels: size/M, kind/feature

#30 PR-30: update services for rq workers to work
  .github/workflows/tests.yml
  resources/systemd/rb-aioutliers-rq.service
  resources/systemd/rb-aioutliers-train.service
  resources/systemd/rb-aioutliers.service
Labels: enhancement, kind/documentation, size/S

#31 PR-31: Fix model loss
  resources/src/ai/outliers.py
  resources/src/ai/trainer.py
Labels: bug, size/XS

#32 PR-32: Fix codecov
  .github/workflows/tests.yml
  README.md
Labels: bug

#34 PR-33: Fix software LICENSE
  LICENSE
  README.md
  resources/src/__main__.py
  resources/src/ai/outliers.py
  resources/src/ai/trainer.py
  resources/src/config/configmanager.py
  resources/src/druid/client.py
  resources/src/druid/query_builder.py
  resources/src/logger/logger.py
  resources/src/rbntp/ntplib.py
  resources/src/redborder/async_jobs/train_job.py
  resources/src/redborder/rq.py
  resources/src/redborder/s3.py
  resources/src/server/production.py
  resources/src/server/rest.py
  resources/tests/test_configmanager.py
  resources/tests/test_druid.py
  resources/tests/test_logger.py
  resources/tests/test_ntp.py
  resources/tests/test_outliers.py
  resources/tests/test_query_builder.py
  resources/tests/test_rq.py
  resources/tests/test_s3.py
  resources/tests/test_train_job.py
  resources/tests/test_trainer.py
Labels: documentation, licenses

#37 PR-36: Improved base model and rb_aioutliers handling of the different granularities
  resources/src/ai/outliers.py
  resources/src/ai/traffic.ini
  resources/src/ai/traffic.keras
  resources/src/ai/trainer.py
  resources/tests/model_test.keras
  resources/tests/model_test_config.ini
Labels: size/M, kind/feature

#38 PR-37: Update spec file license to GPL 2.0
  packaging/rpm/rb-aioutliers.spec
Labels: size/XS, licenses
