Repository redBorder/rb-aioutliers, pull requests merged in 2024-01, with the labels that each got.

#42 PR-39: Add default model logic to the api
  resources/src/ai/outliers.py
  resources/src/ai/shallow_outliers.py
  resources/src/ai/traffic.ini
  resources/src/ai/trainer.py
  resources/src/requirements.txt
  resources/src/server/rest.py
  resources/tests/test_rest.py
  resources/tests/test_trainer.py
Labels: kind/feature, size/L

#44 PR-40: Add dynamic filters
  .github/workflows/security.yml
  resources/src/__main__.py
  resources/src/ai/outliers.py
  resources/src/ai/shallow_outliers.py
  resources/src/ai/traffic_filter.json
  resources/src/ai/trainer.py
  resources/src/config.ini
  resources/src/config/configmanager.py
  resources/src/druid/client.py
  resources/src/druid/query_builder.py
  resources/src/logger/logger.py
  resources/src/redborder/async_jobs/train_job.py
  resources/src/redborder/rq.py
  resources/src/server/rest.py
  resources/tests/test_configmanager.py
  resources/tests/test_druid.py
  resources/tests/test_logger.py
  resources/tests/test_ntp.py
  resources/tests/test_outliers.py
  resources/tests/test_query_builder.py
  resources/tests/test_rest.py
  resources/tests/test_rq.py
  resources/tests/test_s3.py
  resources/tests/test_shallow_outliers.py
  resources/tests/test_train_job.py
  resources/tests/test_trainer.py
Labels: kind/feature, size/XL

#45 PR-41: RedHat 9 Version of rb-aioutliers
  README.md
  packaging/rpm/rb-aioutliers.spec
  resources/systemd/rb-aioutliers-rq.service
  resources/systemd/rb-aioutliers-train.service
  resources/systemd/rb-aioutliers.service
  resources/tests/test_rq.py
Labels: feature, size/M
