Repository redBorder/rb-aioutliers, pull requests merged in 2024-02, with the labels that each got.

#46 PR-42: Fix performance issues
  resources/src/__main__.py
  resources/src/ai/outliers.py
  resources/src/ai/shallow_outliers.py
  resources/src/server/rest.py
  resources/tests/test_outliers.py
  resources/tests/test_rest.py
Labels: kind/bug, size/L

#47 PR-43: Add release workflow
  .github/workflows/changelog.yml
  .github/workflows/release.yml
Labels: kind/documentation, size/L

#49 PR-45: Update changelog workflow
  .github/workflows/changelog.yml
Labels: kind/documentation, size/XS

#50 PR-46 - Update changelog
  .github/workflows/changelog.yml
Labels: kind/documentation, size/XS

#52 PR-48: Fix doxygen action
  .github/workflows/doxygen.yml
  Doxyfile
Labels: kind/documentation, size/S

#53 pr-49: Reconfigure doxyfile
  Doxyfile
Labels: size/XS

#54 PR-50: Fix work path
  .github/workflows/doxygen.yml
Labels: size/XS

#55 PR-51: Optimize doxygen
  .github/workflows/doxygen.yml
  Doxyfile
Labels: size/S

#56 PR-52: Update doxyfile and create mainpage
  Doxyfile
  resources/src/RBAIOUTLIERS.md
Labels: kind/documentation, size/S

#57 PR-52: Update doxyfile
  .github/workflows/doxygen.yml
Labels: kind/documentation, size/XS

#59 PR-55: Update path
  .github/workflows/doxygen.yml
Labels: kind/documentation, size/XS
